# -*- coding: utf-8 -*-
"""ML_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lU8vYKWoWAACBjaZGl40k6DGYqfk09I
"""

import os

for file in os.listdir():
    if file.endswith(".csv"):
        print(file)

import pandas as pd
import numpy as np

train = pd.read_csv("IMT2024010_train_var1.csv")
test = pd.read_csv("IMT2024010_test_var1.csv")

data = train.to_numpy()
test_data = test.to_numpy()

data.size

test.size

data[0].size

X = data[:,:-1]

Y = data[:,-1]

from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=42)

"""We Try Polynomial Features degree(1-10) with interaction terms as well as without interaction terms and check the results"""

def polynomial_features(X, degree):
    X_poly = []

    # Bias term
    X_poly.append(np.ones((X.shape[0], 1)))

    for d in range(1, degree + 1):
        X_poly.append(X ** d)

    return np.concatenate(X_poly, axis=1)

def polynomial_features_interaction(X, degree):
    n_samples, n_features = X.shape
    X_poly = []

    # Bias / intercept term
    X_poly.append(np.ones(n_samples))

    # Generate all exponent combinations
    def generate_exponents(pos, remaining, exponents):
        if pos == n_features - 1:
            exponents.append(remaining)
            yield exponents
            exponents.pop()
            return

        for power in range(remaining + 1):
            exponents.append(power)

            yield from generate_exponents(
                pos + 1,
                remaining - power,
                exponents
            )

            exponents.pop()

    # Generate terms of each total degree
    for d in range(1, degree + 1):
        for powers in generate_exponents(0, d, []):
            term = np.ones(n_samples)

            for j in range(n_features):
                if powers[j] > 0:
                    term *= X[:, j] ** powers[j]

            X_poly.append(term)

    return np.array(X_poly).T

def fit_linear_regression(X, y):
    beta = np.linalg.lstsq(X, y, rcond=None)[0]

    return beta

def predict(X, beta):
    return X @ beta

def mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

def r2_score(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)

    return 1 - (ss_res / ss_tot)

"""*For Polynomial features with interaction terms,if we have degree 6, we get more no of parameters than training data points, which will definitely overfit the training data, hence we limit to degree 5.*"""

degrees = range(1, 11)

cv_errors = []
cv_r2_scores = []

for degree in degrees:

    fold_mse = []
    fold_r2 = []

    for train_index, val_index in kf.split(X):

        X_train = X[train_index]
        X_val = X[val_index]

        y_train = Y[train_index]
        y_val = Y[val_index]

        X_train_poly = polynomial_features(X_train, degree)
        X_val_poly = polynomial_features(X_val, degree)

        beta = fit_linear_regression(X_train_poly, y_train)

        y_val_pred = predict(X_val_poly, beta)

        fold_mse.append(mse(y_val, y_val_pred))
        fold_r2.append(r2_score(y_val, y_val_pred))

    mean_mse = np.mean(fold_mse)
    mean_r2 = np.mean(fold_r2)

    cv_errors.append(mean_mse)
    cv_r2_scores.append(mean_r2)

    print(
        f"Degree {degree}: "
        f"5-Fold CV MSE = {mean_mse:.6f}, "
        f"5-Fold CV R² = {mean_r2:.6f}"
    )

degrees = range(1, 11)

cv_errors_interaction = []
cv_r2_interaction = []

for degree in degrees:

    fold_mse = []
    fold_r2 = []

    for train_index, val_index in kf.split(X):

        X_train = X[train_index]
        X_val = X[val_index]

        y_train = Y[train_index]
        y_val = Y[val_index]

        X_train_poly = polynomial_features_interaction(
            X_train, degree
        )

        X_val_poly = polynomial_features_interaction(
            X_val, degree
        )

        beta = fit_linear_regression(
            X_train_poly, y_train
        )

        y_val_pred = predict(
            X_val_poly, beta
        )

        fold_mse.append(
            mse(y_val, y_val_pred)
        )

        fold_r2.append(
            r2_score(y_val, y_val_pred)
        )

    mean_mse = np.mean(fold_mse)
    mean_r2 = np.mean(fold_r2)

    cv_errors_interaction.append(mean_mse)
    cv_r2_interaction.append(mean_r2)

    print(
        f"Degree {degree}: "
        f"5-Fold CV MSE = {mean_mse:.6f}, "
        f"5-Fold CV R² = {mean_r2:.6f}"
    )

import matplotlib
from matplotlib import pyplot as plt

matplotlib.rcParams['figure.dpi'] = 100

plt.figure(figsize=(10, 6))

plt.plot(
    degrees,
    cv_errors,
    marker='o',
    label='5-Fold CV MSE'
)

plt.plot(
    degrees,
    cv_errors_interaction,
    marker='o',
    label='5-Fold CV MSE Interaction'
)

plt.xlabel('Polynomial Degree')
plt.ylabel('MSE')
plt.title('Polynomial Degree Selection using 5-Fold CV')
plt.xticks(list(degrees))
plt.legend()
plt.grid(True)
plt.show()

"""***Degree-4 with interaction terms seems to be the best model***"""

def ridge_regression(X, y, lam):
    n_features = X.shape[1]

    I = np.eye(n_features)
    I[0, 0] = 0

    A = X.T @ X + lam * I
    b = X.T @ y

    beta = np.linalg.solve(A, b)

    return beta

degrees = [1, 2, 3, 4, 5]
lambdas = [0.01, 0.1, 1, 10, 100]

from sklearn.preprocessing import StandardScaler

results = []

for degree in degrees:

    for lam in lambdas:

        fold_mse = []
        fold_r2 = []

        for train_index, val_index in kf.split(X):

            X_train = X[train_index]
            X_val = X[val_index]

            y_train = Y[train_index]
            y_val = Y[val_index]

            X_train_poly = polynomial_features_interaction(
                X_train, degree
            )

            X_val_poly = polynomial_features_interaction(
                X_val, degree
            )

            # Scale everything except bias
            scaler = StandardScaler()

            X_train_scaled = X_train_poly.copy()
            X_val_scaled = X_val_poly.copy()

            X_train_scaled[:, 1:] = scaler.fit_transform(
                X_train_poly[:, 1:]
            )

            X_val_scaled[:, 1:] = scaler.transform(
                X_val_poly[:, 1:]
            )

            beta_l2 = ridge_regression(
                X_train_scaled,
                y_train,
                lam
            )

            pred_l2 = X_val_scaled @ beta_l2

            fold_mse.append(
                mse(y_val, pred_l2)
            )

            fold_r2.append(
                r2_score(y_val, pred_l2)
            )

        mean_mse = np.mean(fold_mse)
        mean_r2 = np.mean(fold_r2)

        results.append(
            [degree, lam, "L2", mean_mse, mean_r2]
        )

        print(
            f"Degree={degree}, "
            f"Lambda={lam}, "
            f"CV MSE={mean_mse:.6f}, "
            f"CV R²={mean_r2:.6f}"
        )

for degree in degrees:

    print("\nDegree:", degree)

    best_mse = float("inf")
    best_lam = None
    best_r2 = None

    for row in results:

        d, lam, name, mse_value, r2_value = row

        if d == degree and name == "L2":

            if mse_value < best_mse:

                best_mse = mse_value
                best_lam = lam
                best_r2 = r2_value

    print(
        "Best lambda:", best_lam,
        "| CV MSE:", best_mse,
        "| CV R²:", best_r2
    )

best_result = min(
    results,
    key=lambda x: x[3]
)

best_degree = best_result[0]
best_lambda = best_result[1]
best_mse = best_result[3]
best_r2 = best_result[4]

print("Best Degree:", best_degree)
print("Best Lambda:", best_lambda)
print("Best CV MSE:", best_mse)
print("Best CV R²:", best_r2)

"""# ***Best Model : Degree 5 with interaction terms and L2 normalisation with lambda=10***"""

test_data.shape

from sklearn.preprocessing import StandardScaler

degree = best_degree
lam = best_lambda

X_test = test_data

X_train_poly = polynomial_features_interaction(
    X, degree
)

X_test_poly = polynomial_features_interaction(
    X_test, degree
)

scaler = StandardScaler()

X_train_scaled = X_train_poly.copy()
X_test_scaled = X_test_poly.copy()

X_train_scaled[:, 1:] = scaler.fit_transform(
    X_train_poly[:, 1:]
)

X_test_scaled[:, 1:] = scaler.transform(
    X_test_poly[:, 1:]
)

print("Training feature matrix:", X_train_scaled.shape)
print("Test feature matrix:", X_test_scaled.shape)

beta_final = ridge_regression(
    X_train_scaled,
    Y,
    lam
)

print("Number of coefficients:", len(beta_final))
print("Intercept:", beta_final[0])

# Predictions on the full training data
y_train_pred = X_train_scaled @ beta_final

# Predictions on the test data
y_test_pred = X_test_scaled @ beta_final

# Training error
train_mse = np.mean((Y - y_train_pred) ** 2)
train_rmse = np.sqrt(train_mse)
train_r2 = r2_score(Y, y_train_pred)

print("Training MSE:", train_mse)
print("Training RMSE:", train_rmse)
print("Training R²:", train_r2)

print("Training predictions:", y_train_pred.shape)
print("Test predictions:", y_test_pred.shape)

plt.figure(figsize=(7, 6))

plt.scatter(Y, y_train_pred, alpha=0.6)

# Ideal prediction line
low = min(np.min(Y), np.min(y_train_pred))
high = max(np.max(Y), np.max(y_train_pred))

plt.plot([low, high], [low, high], 'r--')

plt.xlabel("Actual y")
plt.ylabel("Predicted y")
plt.title("Degree 5 Ridge Regression: Actual vs Predicted")
plt.grid(True)
plt.show()

residuals = Y - y_train_pred

plt.figure(figsize=(8, 5))

plt.scatter(y_train_pred, residuals, alpha=0.6)
plt.axhline(y=0, color='r', linestyle='--')

plt.xlabel("Predicted y")
plt.ylabel("Residual")
plt.title("Degree 5 Ridge Regression: Residual Plot")
plt.grid(True)
plt.show()

predictions = pd.DataFrame({
    "y": y_test_pred
})

predictions.to_csv("degree5_ridge_predictions.csv", index=False)

print("Saved degree5_ridge_predictions.csv")